### ISSUE TITLE
test coverage should be reported from CI

### ISSUE THREAD

**Issue by barmintor** [samvera/solrizer#46]

**Comment by cam156** [comment]
@barmintor the text coverage is showing on the last merged pr at 98%: https://github.com/samvera/solrizer/pull/44

Not sure why this is opened???

**Comment by barmintor** [comment]
@cam156 we were opening these on all the candidate projects at one point while we sorted out how to track this work - it's not an indictment! Likewise, the "sufficient" ticket is a judgment call - it's something we're asking all the product owners to assess. I'm sorry if these caused undue concern.

**Comment by barmintor** [comment]
See also https://waffle.io/samvera-labs/maintenance
