### ISSUE TITLE
Identify New Product Owner

### ISSUE THREAD

**Issue by tpendragon** [samvera/solrizer#54]
@carolyncole has moved to a different position, so we'll need to fill this.

**Comment by jrgriffiniii** [comment]
The e-mail message for this has been drafted and submitted to the samvera-tech mailing list.

**Comment by jrgriffiniii** [comment]
If this is best left to deprecation, I can follow this message with a call for deprecation (following the process outlined in https://samvera.github.io/deprecation.html#deprecation-process-from-core).
